# Aidan McCoy

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Band;
DROP TABLE IF EXISTS Instruments;
DROP TABLE IF EXISTS Performance;
DROP TABLE IF EXISTS Songs;
DROP TABLE IF EXISTS Tracklist;
DROP TABLE IF EXISTS Vocals;
SET FOREIGN_KEY_CHECKS = 1;
