# Aidan McCoy

CREATE TABLE Marathon (
Place VARCHAR(10),
Time VARCHAR(10),
Pace VARCHAR(10),
GrpPlace VARCHAR(10),
Grp VARCHAR(10),
Age CHAR(2),
Sex CHAR(1),
BibNumber VARCHAR(10),
FirstName VARCHAR(100),
LastName VARCHAR(100),
Town VARCHAR(100),
State VARCHAR(100));
